### PR TITLE
Add SelfUpdate parameter (FATE#319716)

### PR DESCRIPTION
**Pull request by imobach**
* This parameter enables/disables/configures self-update feature.

### CODE REVIEW

**Comment by wfeldt** [comment]
Imo: ok, but it doesn't do anything with the url. Will this change or do you just pass the url? If so,
it might be better not to parse and rebuild the url as this ties you to the linuxrc url schemes.

**Comment by imobach** [comment]
@wfeldt The idea is only to pass the URL as is. I though in using `url_*` functions as some kind of "validator". But thinking it twice, you're right. I'll simplify things a bit. Thanks for the review.

**Comment by imobach** [comment]
I've changed the handling of the URL as you suggested.

I've also added the `Insecure` parameter to `/etc/install.inf` as it's needed by FATE#319716. I though writing `Insecure` as `!config.secure` but I realized that it can be changed [during boot](https://github.com/openSUSE/linuxrc/blob/b904083833ebed372a301d3b544e95134c26fbe2/url.c#L1578) and I don't want that change to affect the self-update feature. For example, you can add your own insecure DUD but sure you'll want the official self-update to be checked.

**Comment by wfeldt** [comment]
I don't understand this insecure/secure thing. Once you skipped one signature check, there's really no point checking any again. You system **has** already been compromised. Or not?

BTW, this is the very reason why linuxrc never accepts anything like insecure=0.

**Comment by imobach** [comment]
@wfeldt Sorry, I've just removed too much :(

**Comment by wfeldt** [comment]
lgtm

**Comment by imobach** [comment]
@wfeldt Thanks!

**Pull request merged**
