### PR TITLE
Append EXTRA_CFLAGS to CFLAGS.

### PR DESCRIPTION
**Pull request by marxin**
I would like the package would respect $Optflags in OBS.
Thus I'm suggesting to append EXTRA_CFLAGS to CFLAGS. One can
then 'export EXTRA_CFLAGS=$Optflags'.

### CODE REVIEW

**Comment by marxin** [comment]
Which is probably what was already suggested in https://github.com/openSUSE/linuxrc/pull/154.

**Comment by wfeldt** [comment]
Doesn't simply adding `$(RPM_OPT_FLAGS)` do what you want?

**Comment by marxin** [comment]
> Doesn't simply adding `$(RPM_OPT_FLAGS)` do what you want?

That would work. So should I add the `$(RPM_OPT_FLAGS)` to `CFLAGS` in the `Makefile`?

**Comment by wfeldt** [comment]
if you change this pr, that would be ok

**Comment by marxin** [comment]
> if you change this pr, that would be ok

Good, done.

**Pull request merged**
