### PR TITLE
fix network url handling (fate #318899)

### PR DESCRIPTION
**Pull request by wfeldt**

### CODE REVIEW

**Comment by markkp** [comment]
I'm not understanding what this change has to do with the feature for installation from the HMC DVD.

**Comment by wfeldt** [comment]
It's an implementation bug for handling network urls.

**Comment by kobliha** [comment]
Then @markkp is right that you should not reference a HMC feature but a bug describing the problem which is fixed by this PR.

**Comment by wfeldt** [comment]
Ok, see bug 970927.

**Pull request merged**
