### PR TITLE
Add support for gz and zst compressed modules

### PR DESCRIPTION
**Pull request by mwilck**
Add .ko.gz and .ko.zst to the mod_extensions array. Thanks for
having coded this with future extension in mind!

### CODE REVIEW

**Comment by wfeldt** [comment]
Thanks!

Is this just prophylactic or do kernel packages using zstd already exist / are planned for?

**Comment by mwilck** [comment]
At the moment, it's prophylactic. Prophylactic pactches are also on the way for suse-module-tools and the kernel itself. I have started the discussion on switching the kernel package to zstd on the suse kernel ML recently. Adding support to linuxrc would be one prerequisiste.

**Comment by wfeldt** [comment]
mkdud and mksuse will also need adjustments.

Please keep in mind that whenever this is going to go into SLE, a bug or Jira number will be needed.

**Review by wfeldt — APPROVED** [review]
lgtm

**Comment by mwilck** [comment]
So far there's just jsc#PM-2971.

**Pull request merged**
