### PR TITLE
fix rescue image in usrmerge case (boo#1029961)

### PR DESCRIPTION
**Pull request by lnussel**
Do not create directories in / that are subject to usrmerge

### CODE REVIEW

**Comment by lnussel** [comment]
could be that the code is not needed at all. after all it doesn't create lib64 either

**Comment by wfeldt** [comment]
Shouldn't that be a run-time decision, not compile-time?

**Comment by lnussel** [comment]
depends on the use case. Do you expect linuxrc to load legacy images?

**Comment by wfeldt** [comment]
Yes, linuxrc typically covers a few releases as there are strange backport requests and also people merging products (think of microos mixing sle15-sp2 and sp3).

And also I'd like to develop and compile on a different system than the test system. :-)

**Comment by lnussel** [comment]
ok in that case I'd probably not create those dirs there at all. They will be in one of the images anyway

**Comment by wfeldt** [comment]
Possibly; it's very old code.

**Comment by lnussel** [comment]
confirmed rescue image still works without those dirs created by linuxrc

The travis fail looks unrelated

**Review by wfeldt — APPROVED** [review]
let's try it

**Pull request merged**
